### ISSUE TITLE
Missing or confusing links to meta-analysis publications

### ISSUE THREAD

**Issue by lottiegasp** [langcog/metalab#16]
We received feedback that the links to meta-analysis publications are missing or confusing. I suggest all datasets have a line indicating the publication status, so users aren't confused when a link is missing.

e.g. Unpublished: Repository{with link}
Preprint: Paper{with link}, Repository{with link to osf etc}
Published: Paper{with link to article}, Repository{with link to osf etc}

I'm listing below all those that need changes made:

- [x] Abstract rule learning- link to Rabagliati et al (2018) doesn't open. Add link to journal article]
- [x] Categorization bias - no link to a paper. is there a paper in progress and if so, link to the repository?
- [x] Cross situational word learning - no link to Dal Ben et al. (2019)
- [x] Familiar word recognition - no link to Carbajal (2018)
- [x] Function word segmentation - "Published:[Bergmann & Cristia (2015)](https://onlinelibrary.wiley.com/doi/abs/10.1111/desc.12341), [Database](https://sites.google.com/site/inworddb/)"
- [x] Gaze following - link to Frank, Lewis, & MacDonald (2016) no longer works. find and add new link
- [x] Label advantage in concept learning - add link to repository of Lewis & Long (unpublished)?
- [x] Mispronunciation sensitivity - links to a drive without paper, so add label: Unpublished: Repository{with link}
- [x] Mutual exclusivity: add label "Published: [Lewis et al. (2020)](https://psyarxiv.com/wsx3a/download?format=pdf)"
- [x] Natural speech preference - links to a spreadsheet, so add label "Unpublished: Repository{with link}"
- [x] Phonotactic learning - find out status and link to Cristia (2018)
- [x] Prosocial agents - "Published: [Margoni & Surian (2018)](https://psycnet.apa.org/fulltext/2018-33347-001.pdf)"
- [x] Sound symbolism - link doesn't work find link to Lammertink et al. (2016)
- [x] Statistical sound category learning - find out status and link to Cristia (2018)
- [x] Statistical word segmentation - link to Github. add link to paper or indicate Unpublished
- [x] Switch Task - link to a drive. add link to paper or indicate Unpublished
- [x] Vowel discrimination (native): Add "Published: [Tsuji & Cristia (2014)](https://pure.mpg.de/rest/items/item_1836135/component/file_1945376/content), [Database](https://sites.google.com/site/inphondb/)"
- [x] Vowel discrimination (non-native): Add "Published: [Tsuji & Cristia (2014)](https://pure.mpg.de/rest/items/item_1836135/component/file_1945376/content), [Database](https://sites.google.com/site/inphondb/)"
- [x] Word segmentation: "Published: [Bergmann & Cristia (2015)](https://onlinelibrary.wiley.com/doi/abs/10.1111/desc.12341), Database](https://sites.google.com/site/inworddb/)"

**Comment by christinabergmann** [comment]
As discussed in our meeting, this is a great opportunity to also add additional information:
Link to additional information like search protocol, Prisma chart, and maybe external websites.

**Comment by lottiegasp** [comment]
@christinabergmann would this involve adding new fields to the metadata/datasets.yaml ?

**Comment by christinabergmann** [comment]
Yes, I'd say so.

**Comment by lottiegasp** [comment]
I will create new Issue for adding new fields to the metadata/datasets.yaml like search protocol, Prisma chart, and external websites, as the original Issue of missing/confusing links has been resolved
